
spring:
  application:
    name: springcloud-gateway
  profiles:
    active: springcloud-gateway-1900

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://10.2.11.3:8761/eureka, http://10.2.11.3:8762/eureka, http://10.2.11.3:8763/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

---
server:
  port: 1900
spring:
  profiles: springcloud-gateway-1900

---
server:
  port: 1901
spring:
  profiles: springcloud-gateway-1901

---
server:
  port: 1902
spring:
  profiles: springcloud-gateway-1902
