

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://10.2.11.3:8761/eureka, http://10.2.11.3:8762/eureka, http://10.2.11.3:8763/eureka

spring:
  application:
    name: springcloud-user
  profiles:
    active: springcloud-user-2000
server:
  servlet:
    context-path: /user
feign:
  hystrix:
    enabled: true

---
server:
  port: 2000
spring:
  profiles: springcloud-user-2000

---
server:
  port: 2001
spring:
  profiles: springcloud-user-2001

---
server:
  port: 2002
spring:
  profiles: springcloud-user-2002