
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://10.2.11.3:8761/eureka, http://10.2.11.3:8762/eureka, http://10.2.11.3:8763/eureka

spring:
  application:
    name: springcloud-comment
  profiles:
    active: springcloud-comment-2300
server:
  servlet:
    context-path: /comment

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /comment

hystrix:
  command:
    default:
      execution:
        timeout:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

---
server:
  port: 2300
spring:
  profiles: springcloud-comment-2300

---
server:
  port: 2301
spring:
  profiles: springcloud-comment-2301

---
server:
  port: 2302
spring:
  profiles: springcloud-comment-2302